#ifndef GUARD_CONSTANTS_POKEMON_ICON_H
#define GUARD_CONSTANTS_POKEMON_ICON_H

#define POKE_ICON_BASE_PAL_TAG 56000
#define POKE_ICON_SILHOUETTE_PAL_TAG POKE_ICON_BASE_PAL_TAG - 1

#endif  // GUARD_CONSTANTS_POKEMON_ICON_H
