#ifndef GUARD_POKEMON_AMIE_H
#define GUARD_POKEMON_AMIE_H

#define AR_ENABLE_AMIE_REFRESH  TRUE
#define AR_ENABLE_AMIE_FLAG     FLAG_UNUSED_0x863
#define AR_FACE_AWAY_CHANCE     20

#endif // GUARD_POKEMON_AMIE_H