#ifndef GUARD_POKEMON_AMIE_H
#define GUARD_POKEMON_AMIE_H

#define AR_ENABLE_AMIE_REFRESH  TRUE
#define AR_ENABLE_AMIE_FLAG     FLAG_UNUSED_0x863
#define AR_TRACK_LAST_AMIE_MON  TRUE

#endif // GUARD_POKEMON_AMIE_H