SpaMountain_MapScripts::
	.byte 0


SpaMountain_EventScript_Rattata::
# 6 "data/maps/SpaMountain/scripts.pory"
	lock
# 7 "data/maps/SpaMountain/scripts.pory"
	startspa 0
# 8 "data/maps/SpaMountain/scripts.pory"
	releaseall
	end


SpaMountain_EventScript_Teddiursa::
# 13 "data/maps/SpaMountain/scripts.pory"
	lock
# 14 "data/maps/SpaMountain/scripts.pory"
	startspa 1
# 15 "data/maps/SpaMountain/scripts.pory"
	releaseall
	end


SpaMountain_EventScript_Psyduck::
# 20 "data/maps/SpaMountain/scripts.pory"
	lock
# 21 "data/maps/SpaMountain/scripts.pory"
	startspa 2
# 22 "data/maps/SpaMountain/scripts.pory"
	releaseall
	end


SpaMountain_EventScript_Fletchinder::
# 27 "data/maps/SpaMountain/scripts.pory"
	lock
# 28 "data/maps/SpaMountain/scripts.pory"
	startspa 3
# 29 "data/maps/SpaMountain/scripts.pory"
	releaseall
	end


SpaMountain_EventScript_Lombre::
# 34 "data/maps/SpaMountain/scripts.pory"
	lock
# 35 "data/maps/SpaMountain/scripts.pory"
	startspa 4
# 36 "data/maps/SpaMountain/scripts.pory"
	releaseall
	end

